openapi: 3.1.0
info:
  title: Lunch Picker API
  version: 0.1.0
servers:
  - url: /api
paths:
  /search:
    post:
      summary: Search for lunch spots
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRequest'
            example:
              location:
                lat: 35.681236
                lng: 139.767125
              radius_m: 1000
              cuisine: ['ラーメン', 'カレー']
              budget:
                max: 1500
              limit: 5
      responses:
        '200':
          description: List of restaurants
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
              example:
                results:
                  - place_id: ChIJ51cu8IcbXWARiRtXIothAS4
                    name: シャングリ・ラ 東京
                    rating: 4.5
                    distance_m: 243
                    price_level: PRICE_LEVEL_EXPENSIVE
                    open_now: true
                    fit_score: 0.874
                    static_map_url: /api/maps/static?lat=35.679722&lng=139.765833&placeId=ChIJ51cu8IcbXWARiRtXIothAS4
                    gmaps_url: https://www.google.com/maps/search/?api=1&query=35.679722,139.765833
                    address: 東京都千代田区丸の内1-8-3
                    types: ['restaurant', 'food', 'point_of_interest', 'establishment']
                  - place_id: ChIJRYKKxLcRGGARoITz9yDB0Ns
                    name: 東京ラーメンストリート
                    rating: 4.2
                    distance_m: 520
                    price_level: PRICE_LEVEL_MODERATE
                    open_now: false
                    fit_score: 0.756
                    static_map_url: /api/maps/static?lat=35.681944&lng=139.767222&placeId=ChIJRYKKxLcRGGARoITz9yDB0Ns
                    gmaps_url: https://maps.google.com/?cid=15544893621850219168
                    address: 東京都千代田区丸の内1-9-1
                    types: ['restaurant', 'food', 'point_of_interest', 'establishment']
                cachedAt: 1729267200000
components:
  schemas:
    Coordinates:
      type: object
      required:
        - lat
        - lng
      properties:
        lat:
          type: number
        lng:
          type: number
    SearchRequest:
      type: object
      required:
        - location
        - radius_m
      properties:
        location:
          $ref: '#/components/schemas/Coordinates'
        radius_m:
          type: integer
          minimum: 0
        cuisine:
          type: array
          items:
            type: string
          default: []
        budget:
          anyOf:
            - type: 'null'
            - type: object
              required:
                - max
              properties:
                max:
                  type: number
        limit:
          type: integer
          minimum: 1
          default: 5
    SearchResult:
      type: object
      required:
        - place_id
        - name
        - gmaps_url
        - distance_m
        - static_map_url
        - fit_score
        - types
      properties:
        place_id:
          type: string
        name:
          type: string
        rating:
          type: number
          nullable: true
        distance_m:
          type: number
        price_level:
          type: string
          nullable: true
        open_now:
          type: boolean
          nullable: true
        fit_score:
          type: number
          description: Combined score derived from rating, distance, price level, and open state.
        static_map_url:
          type: string
        gmaps_url:
          type: string
        address:
          type: string
          nullable: true
        types:
          type: array
          items:
            type: string
    SearchResponse:
      type: object
      required:
        - results
        - cachedAt
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/SearchResult'
        cachedAt:
          type: integer
          description: Epoch millis when the response was cached.
