/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Lunch Picker API
 * OpenAPI spec version: 0.1.0
 */
import type { SearchResult } from './searchResult';

export interface SearchResponse {
  results?: SearchResult[];
}
