/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Lunch Picker API
 * OpenAPI spec version: 0.1.0
 */

export interface SearchResult {
  distance_m?: number;
  gmaps_url: string;
  name: string;
  price_level?: string;
  rating?: number;
  static_map_url?: string;
}
