/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Lunch Picker API
 * OpenAPI spec version: 0.1.0
 */
import type { SearchRequestBudget } from './searchRequestBudget';
import type { Coordinates } from './coordinates';

export interface SearchRequest {
  budget?: SearchRequestBudget;
  cuisine?: string[];
  /** @minimum 1 */
  limit?: number;
  location: Coordinates;
  /** @minimum 0 */
  radius_m: number;
}
