/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Lunch Picker API
 * OpenAPI spec version: 0.1.0
 */

export interface SearchResult {
  /** @nullable */
  address?: string | null;
  distance_m: number;
  /** Combined score derived from rating, distance, price level, and open state. */
  fit_score?: number;
  gmaps_url: string;
  name: string;
  /** @nullable */
  open_now?: boolean | null;
  place_id: string;
  /** @nullable */
  price_level?: string | null;
  /** @nullable */
  rating?: number | null;
  static_map_url: string;
  types?: string[];
}
