/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Lunch Picker API
 * OpenAPI spec version: 0.1.0
 */
import type { SearchRequestBudgetAnyOf } from './searchRequestBudgetAnyOf';

export type SearchRequestBudget = null | SearchRequestBudgetAnyOf;
