# Production deployment config. See docs/deployment.md for setup instructions.
name = "lunch-picker-api"
main = "src/index.ts"
compatibility_date = "2025-10-01"
workers_dev = true

[vars]
NODE_ENV = "production"
# GOOGLE_PLACES_API_KEY is provided via `.dev.vars` in development or Wrangler secrets in production.

[[d1_databases]]
binding = "DB"
database_name = "lunch-picker"
# Provide the production database_id via apps/api/wrangler.toml.local (git-ignored).
database_id = "d8cd5a46-c41c-4f1d-81a9-7e54a74751be"
preview_database_id = "04b28b20-92cc-42a9-8bda-cd2d334fb983"

[[kv_namespaces]]
binding = "CACHE"
# Provide the production namespace id via apps/api/wrangler.toml.local (git-ignored).
id = "35e80932533f4a48b99428179ef266e0"
preview_id = "f14958225d9840e0ac841496099f53ab"
